// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProduct struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type NewUser struct {
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	BusinessUnit string `json:"businessUnit"`
}

type Product struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type Query struct {
}

type User struct {
	ID           string `json:"id"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	BusinessUnit string `json:"businessUnit"`
}
