// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID           string  `json:"id"`
	FirstName    *string `json:"firstName,omitempty"`
	LastName     *string `json:"lastName,omitempty"`
	BusinessUnit *string `json:"businessUnit,omitempty"`
}

func (User) IsEntity() {}

type UserInput struct {
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	BusinessUnit string `json:"businessUnit"`
}
